### ISSUE TITLE
Missing subfolders images and progbarstyles

### ISSUE THREAD

**Issue by ThomasVogelpohl** [KhoaTranProgrammer/ProgressBarCollection#1]
Hi KhoaTranProgrammer, 
it seems your repo is missing the subfolders images and progbarstyles.

Could you add them ?

Thanks,
Thomas

**Comment by KhoaTranProgrammer** [comment]
Hi Thomas,

I've added these folder. Please try again.
Tell me if there is any issue(s)

Best regards,
Khoa
